"""chat sessions, notifications, scheduler lock

Revision ID: 21a3c8d6a8b0
Revises: 9654dfa3c474
Create Date: 2026-08-16 15:42:22.947330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a3c8d6a8b0'
down_revision: Union[str, Sequence[str], None] = '9654dfa3c474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduler_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holder', sa.String(), nullable=True),
    sa.Column('expires_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_lock')
    op.drop_table('notifications')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
