"""initial schema

Revision ID: 9654dfa3c474
Revises:
Create Date: 2026-08-09 19:36:54.039278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9654dfa3c474"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "act_notify_state",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("last_notified_date", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "act_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("answers", sa.String(), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "family_access",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_table(
        "medicine",
        sa.Column("medicine_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("medicine_name", sa.String(), nullable=False),
        sa.Column("dose", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("medicine_id"),
        sa.UniqueConstraint("medicine_name", name="uq_medicine_name"),
    )
    op.create_table(
        "reminders",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=True),
        sa.Column("minute", sa.Integer(), nullable=True),
        sa.Column("last_sent", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_location",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("city_label", sa.String(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_profile",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("smoking", sa.String(), nullable=True),
        sa.Column("allergies", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("surname", sa.String(), nullable=True),
        sa.Column("birth_date", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "extra_info",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("sport", sa.Boolean(), nullable=False),
        sa.Column("sickness", sa.Boolean(), nullable=False),
        sa.Column("stress", sa.Boolean(), nullable=False),
        sa.Column("allergy", sa.Boolean(), nullable=False),
        sa.Column("flight", sa.Boolean(), nullable=False),
        sa.Column("attacks_count", sa.Integer(), nullable=False),
        sa.Column("record_time", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "readings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("first_try", sa.Float(), nullable=False),
        sa.Column("second_try", sa.Float(), nullable=False),
        sa.Column("third_try", sa.Float(), nullable=False),
        sa.Column("maximum", sa.Float(), nullable=False),
        sa.Column("green_zone", sa.Float(), nullable=True),
        sa.Column("yellow_zone", sa.Float(), nullable=True),
        sa.Column("red_zone", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "taken_medicine",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("medicine_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("doses", sa.Integer(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["medicine_id"],
            ["medicine.medicine_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "treatment_plan",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("baseline_therapy", sa.String(), nullable=True),
        sa.Column("worsening_therapy", sa.String(), nullable=True),
        sa.Column("attack_therapy", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("taken_medicine")
    op.drop_table("readings")
    op.drop_table("extra_info")
    op.drop_table("users")
    op.drop_table("user_profile")
    op.drop_table("user_location")
    op.drop_table("reminders")
    op.drop_table("medicine")
    op.drop_table("family_access")
    op.drop_table("act_results")
    op.drop_table("act_notify_state")
    op.drop_table("treatment_plan")
    # ### end Alembic commands ###
