<|vq_14443|>from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'your_revision_id'
down_revision = 'your_down_revision_id'
branch_labels = None
depends_on = None


def upgrade():
    # commands auto generated by Alembic
    pass


def downgrade():
    # commands auto generated by Alembic
    pass
